### PR TITLE
Ryan's requests

### PR DESCRIPTION
**Pull request by phadej**
- ghc-options for local packages
- ${BENCH} in new-test invocations (to not change the build-plan)
- toggle of --no-tests --no-benchmarks step (saves time for big
  projects)

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Does `cfgNoTestsNoBench` also set `INSTALLED` to false?

**Comment by phadej** [comment]
> Does cfgNoTestsNoBench also set INSTALLED to false?

*No*.

I'll make a separate flag for that too.

**Comment by phadej** [comment]
ping @RyanGlScott , there is another toggle now.

**Comment by RyanGlScott** [comment]
Thanks! I can try this out when I get home tonight.

**Comment by phadej** [comment]
@RyanGlScott I'll merge this. Let's make more changes if needed.

**Pull request merged**
