### PR TITLE
Got rid of everything implying make_travis_yml_2.hs works with runghc.

### PR DESCRIPTION
**Pull request by merijn**
Since make_travis_yml_2.hs hasn't worked properly in months I got rid of all the various bits implying it does.

### CODE REVIEW

**Comment by hvr** [comment]
I'm not totally opposed, but I do wonder: what exactly didn't work? I just tried, and `runghc ./make_travis_yml_2.hs` did work for me.

**Comment by merijn** [comment]
I might've been confusing the shebang being broken with runghc not working either. Although runghc seems to fail here with a whole bunch of hidden package warnings on my machine too.

**Comment by phadej** [comment]
```
[FL973] ~/Documents/other-haskell/multi-ghc-travis master % runghc-7.8.4 ./make_travis_yml_2.hs -h 

make_travis_yml_2.hs:90:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,9,0)
     ^

make_travis_yml_2.hs:1278:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,9,0)
     ^
phase `C pre-processor' failed (exitcode = 1)
[FL973] ~/Documents/other-haskell/multi-ghc-travis master % runghc-7.10.3 ./make_travis_yml_2.hs -h

make_travis_yml_2.hs:90:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,9,0)
     ^

make_travis_yml_2.hs:1278:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,9,0)
     ^
phase `C pre-processor' failed (exitcode = 1)
[FL973] ~/Documents/other-haskell/multi-ghc-travis master % runghc-8.0.2 ./make_travis_yml_2.hs -h 
*ERROR* unrecognized option `-h'

Usage: runghc make_travis_yml_2.hs [OPTIONS] <cabal-file | cabal.project> <extra-apt-packages...>
```

**Comment by phadej** [comment]
i.e. doesn't work with GHC-7.* series

**Comment by merijn** [comment]
It wasn't working for 8.0.2 on my OSX system either.

**Comment by phadej** [comment]
Clang's cpp probably causing problems...

**Comment by merijn** [comment]
Well it was complaining about a whole bunch of hidden package from Cabal-1.24, which could be caused by me having both Cabal-1.24 and Cabal-2.0?

**Comment by phadej** [comment]
If your global database has anything else than what's with GHC, all odds are off.

Don't **ever** `cabal install` anything (only in sandbox!), use `new-build`. You can get recent-ish `cabal-install` from https://haskell.futurice.com/

**Comment by merijn** [comment]
Well, that was one of my reasons for nudging people towards using the cabal build version of make-travis-yml over runghc :p

**Pull request closed without merging**
